sudo: false # route your build to the container-based infrastructure for a faster build
language: node_js
node_js:
  - lts/*

before_install:
  - npm i -g @codedoc/cli
  - codedoc install

# Assume bundler is being used, therefore the `install` step will run `bundle install` by default.
script:
  - cd $TRAVIS_BUILD_DIR/content-downloader
  - npm install
  - npm link
  - codedoc-content-downloader
  - cd ..
  - codedoc build
  - cp favicon.ico dist

cache: npm

deploy:
  provider: firebase
  message: "travis ci build #$TRAVIS_BUILD_NUMBER tagged deployment for $TRAVIS_COMMIT"
  token:
    secure: "jS+fVrx+IsRyJ3IIMWdbpiPxQYOM1GmfVUZsZiN+X2N5JFl5aZKYq03LWyr/zWgelwmkJ5N7WqFNzfzpPq0k77f8LSJB4rOe5dFsDhsU/f+selHGtupW4Ecca45+hG8G4AHjooPgJ/kvGxRcErSesQmTGk5AvMCUaJ1XlmO8ycONbbnDHFbfA5Uo25dsUl0rOl8EAfNsPKOMhOL3bwJHizio3sSFTyrZmh8ikzBmlRAgtapGQ8rYpAzWD2MkRQtdjT3ljwQnO1mSlELbnRJ2vyP9UY2erhMJ6s+xm0sVk2vR5I9oxHrjZgt4Eg8sncgrZTD61p6jaNmb49DszSZEqhPFnnCmvSSBI+h+R5kr1djob9vN9VlBB0uFJk1mzG/y6CKFOhaE+RYtucLhWWB7ZYBYcO2OEbS2mvrlOc4doNk3SqkncI2rtcu7r0Q0AVv+nyI2R/i+x5PZlGcd5I4T8JondbQHF3+aZazuRTztROkm5fcWiZ1S0Pr6CF5LJM615BROSkiMq3nbGkUV8tAjMZcdAvy079ZnJ3bwVv387aokv2gjZbux8xSKaXHyRKPKblf2Dw30FxSEPP2NNuXsXUXhj0NgKTQmtfM0JqrgxFusykqm+xiK78TOUqmQ8TYR4q+Zx28LpiATPr7JfYnT81x7hKu7LGn5W0NlY7ncvXY="
  on:
    branch: master
  skip_cleanup: true # otherwise Travis CI will delete all the files created during the build

notifications:
  slack:
    secure: "EZOzU0D6HZDJ2OT9MhVlfycKGW/sJ1mnlnwqJzvFggEiWX7xglXACu0sMYFxPPWeDrNvhIXlYrX/Dc81ZdJzbNkwB1ZN44ZhauK9u4YvzKuCMdt9PG1p5Wx4iYxCeWc+SJUNtY9suY1DRKMSqZtCgxv2tFyPTD+uBC1npTp3NNiNodX5sLIQog0tnxyiKURVQrT78w9Zdmv/A7H02STdb0gikgkUmdb2udUecc/ZRYV+NmH/tFCAlwndVqvgxl+qqjmS2W1Xc8PqQdjO0fEKvc+9FDPODfXDYXdipDnd3VbPFYRDhQkYD1ERCVAg1A3NygL4pIhVwgVfh17Csvj/g4CRxou/rZXhlg0SOwyJlgyAaWyFo7/5DxWtrQqIu24Asv1UXOcGJkzMkEMIfS+iFUZk8bP43mZN9wIMUqfNEtKCEzmnr1lR9ECVfBckMDdMg4meSCgBtRj5G0rvdhK+zzGzoEhfJyXwM14ibs7eLRl9rqdA4ERsXTkIPKXV4Hsj2qejOn99/ojSAv+zRgJB/o8TG9VgKnuldcfKiA6xqeSXinF8rtkok4K6OcW7Kam/6NyqNVP5ul0RGNYWDR1im0uuDPAnbosxUVOgh+YwDRmuNfxXdQU2RwkIahzha5FcEDTa9uANSd0kTtMrcq+k3jRJ4zNmklbjjO7Wxbyb78g="
  email: false
